import { getToken, q, m } from "./auth.mjs";
const BS = String.fromCharCode(92);
const p1 = "C:" + BS + "smoke" + BS + "a.txt";
const p2 = "C:" + BS + "smoke" + BS + "b.txt";
const sessionToken = await getToken();
const k = `smpk${Date.now().toString(36)}r2`;
await m("correos:pickReportar", { sessionToken, key: k, kind: "files", paths: [p1, p2] });
console.log("ok:", JSON.stringify(await q("correos:pickResultado", { sessionToken, key })));
const kBad = `smpk${Date.now().toString(36)}bad`;
await m("correos:pickReportar", { sessionToken, key: kBad, kind: "files", paths: ["nola/ruta/relativa"] });
console.log("relativa filtrada:", JSON.stringify(await q("correos:pickResultado", { sessionToken, key: kBad })));
